;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_text
	.import		_gotoxy
	.import		_solid_line
	.import		_file1
	.import		_file2
	.import		_vport_top
	.import		_vport_bot
	.import		_div_line
	.import		_vport_actv
	.import		_fill_vport
	.export		_drawscrn

; ---------------------------------------------------------------
; void __near__ drawscrn (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_drawscrn: near

.segment	"CODE"

	jsr     _text
	lda     #$00
	jsr     pusha
	ina
	jsr     _gotoxy
	jsr     _solid_line
	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     #$02
	sta     (ptr1)
	lda     #$00
	jsr     pusha
	lda     _div_line
	jsr     _gotoxy
	jsr     _solid_line
	lda     _vport_bot+1
	sta     ptr1+1
	lda     _vport_bot
	sta     ptr1
	lda     _div_line
	sta     (ptr1)
	jsr     _fill_vport
	sta     _file1+1068
	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     _div_line
	ina
	sta     (ptr1)
	lda     _vport_bot+1
	sta     ptr1+1
	lda     _vport_bot
	sta     ptr1
	lda     #$17
	sta     (ptr1)
	jsr     _fill_vport
	sta     _file2+1068
	lda     _vport_actv
	cmp     #$01
	beq     L0020
	cmp     #$02
	beq     L0029
	rts
L0020:	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     #$02
	sta     (ptr1)
	lda     _vport_bot+1
	sta     ptr1+1
	lda     _vport_bot
	sta     ptr1
	lda     _div_line
	sta     (ptr1)
	lda     #$00
	jsr     pusha
	lda     _file1+1068
	jmp     _gotoxy
L0029:	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     _div_line
	ina
	sta     (ptr1)
	lda     _vport_bot+1
	sta     ptr1+1
	lda     _vport_bot
	sta     ptr1
	lda     #$17
	sta     (ptr1)
	lda     #$00
	jsr     pusha
	lda     _file2+1068
	jmp     _gotoxy

.endproc

