;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.forceimport	initmainargs
	.export		_file1
	.export		_file2
	.export		_fip
	.export		_fip1
	.export		_fip2
	.export		_is_ptr
	.export		_div_line
	.export		_vport_actv
	.export		_vport_top
	.export		_vport_bot
	.export		_cursor_y
	.import		_edit
	.import		_init_ed
	.import		_drawscrn
	.import		_send_highlight
	.import		_select
	.import		_deselect
	.import		_move_dn
	.import		_move_up
	.import		_insert
	.import		_delete
	.import		_do_search
	.import		_replace
	.import		_do_save
	.import		_do_load
	.import		_set_div_ln
	.import		_jump
	.import		_gotoline
	.import		_copy
	.import		_paste
	.import		_cut
	.import		_show_fileinfo
	.import		_pagedown
	.import		_pageup
	.import		_quit
	.export		_main

.segment	"DATA"

_fip1:
	.addr	_file1
_fip2:
	.addr	_file2
_div_line:
	.byte	$17
_vport_actv:
	.byte	$01
_vport_top:
	.word	$0022
_vport_bot:
	.word	$0023
_cursor_y:
	.word	$0025

.segment	"BSS"

_file1:
	.res	1077,$00
_file2:
	.res	1077,$00
_fip:
	.res	2,$00
_is_ptr:
	.res	2,$00

; ---------------------------------------------------------------
; int __near__ __cdecl__ main (int, __near__ unsigned char * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldy     #$05
	jsr     pushwysp
	jsr     _init_ed
	lda     _fip1
	ldx     _fip1+1
	jsr     pushax
	jsr     _drawscrn
L009A:	lda     _vport_actv
	cmp     #$01
	bne     L0014
	lda     #>(_file1)
	sta     _fip+1
	lda     #<(_file1)
	bra     L0099
L0014:	lda     #>(_file2)
	sta     _fip+1
	lda     #<(_file2)
L0099:	sta     _fip
	jsr     _edit
	sta     _is_ptr
	stx     _is_ptr+1
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	cmp     #$0A
	beq     L0022
	cmp     #$0B
	beq     L002E
	cmp     #$0D
	beq     L003A
	bra     L0020
L0022:	lda     _is_ptr+1
	sta     ptr1+1
	lda     _is_ptr
	sta     ptr1
	lda     (ptr1)
	cmp     #$A0
	bne     L0020
	jsr     _send_highlight
	stx     tmp1
	ora     tmp1
	beq     L0025
	jsr     _select
	bra     L0020
L0025:	jsr     _move_dn
	bra     L0020
L002E:	lda     _is_ptr+1
	sta     ptr1+1
	lda     _is_ptr
	sta     ptr1
	lda     (ptr1)
	cmp     #$A0
	bne     L0020
	jsr     _send_highlight
	stx     tmp1
	ora     tmp1
	beq     L0031
	jsr     _deselect
	bra     L0020
L0031:	jsr     _move_up
	bra     L0020
L003A:	jsr     _insert
L0020:	lda     _is_ptr+1
	sta     ptr1+1
	lda     _is_ptr
	sta     ptr1
	lda     (ptr1)
	cmp     #$43
	jeq     L006F
	cmp     #$44
	jeq     L0041
	cmp     #$46
	jeq     L0047
	cmp     #$47
	jeq     L0069
	cmp     #$49
	jeq     L0085
	cmp     #$4A
	jeq     L0064
	cmp     #$4C
	jeq     L0059
	cmp     #$50
	jeq     L0075
	cmp     #$51
	jeq     L0093
	cmp     #$52
	beq     L004D
	cmp     #$53
	beq     L0053
	cmp     #$56
	jeq     L0075
	cmp     #$57
	beq     L005F
	cmp     #$58
	jeq     L007F
	cmp     #$63
	beq     L006F
	cmp     #$64
	beq     L0041
	cmp     #$66
	beq     L0047
	cmp     #$67
	beq     L0069
	cmp     #$69
	beq     L0085
	cmp     #$6A
	beq     L0064
	cmp     #$6C
	beq     L0059
	cmp     #$70
	beq     L0075
	cmp     #$71
	beq     L0093
	cmp     #$72
	beq     L004D
	cmp     #$73
	beq     L0053
	cmp     #$76
	beq     L0075
	cmp     #$77
	beq     L005F
	cmp     #$78
	beq     L007F
	cmp     #$8A
	beq     L008B
	cmp     #$8B
	beq     L008F
	jmp     L009A
L0041:	jsr     _delete
	jmp     L009A
L0047:	jsr     _do_search
	jmp     L009A
L004D:	jsr     _replace
	jmp     L009A
L0053:	jsr     _do_save
	jmp     L009A
L0059:	jsr     _do_load
	jmp     L009A
L005F:	jsr     _set_div_ln
	jmp     L009A
L0064:	jsr     _jump
	jmp     L009A
L0069:	jsr     _gotoline
	jmp     L009A
L006F:	jsr     _copy
	jmp     L009A
L0075:	jsr     _paste
	jmp     L009A
L007F:	jsr     _cut
	jmp     L009A
L0085:	jsr     _show_fileinfo
	jmp     L009A
L008B:	jsr     _pagedown
	jmp     L009A
L008F:	jsr     _pageup
	jmp     L009A
L0093:	jsr     _quit
	jmp     L009A

.endproc

