;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_editline2
	.import		_gotoxy
	.import		_strcpy
	.import		_getmem
	.import		_regetmem
	.import		_pack_string
	.import		_expand_string
	.import		_quit
	.import		_bell
	.import		_message
	.import		_waitkey
	.export		_edit

.segment	"RODATA"

L0067:
	.byte	$46,$69,$6C,$65,$20,$65,$72,$72,$6F,$72,$2E,$00
L0035	:=	L0067+0

; ---------------------------------------------------------------
; __near__ struct inpstat * __near__ edit (__near__ struct fileinfo *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_edit: near

.segment	"BSS"

L0005:
	.res	81,$00
L0007:
	.res	81,$00

.segment	"CODE"

	jsr     pushax
	jsr     decsp5
	ldy     #$06
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     sreg
	stx     sreg+1
	lda     #$00
	clc
	ldy     #$05
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	jsr     aslax1
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	jsr     ldaxi
	cpx     #$00
	jne     L0008
	cmp     #$00
	jne     L0008
	ldy     #$04
	sta     (sp),y
L000C:	ldy     #$04
	lda     (sp),y
	cmp     #$51
	bcs     L000D
	pha
	ina
	sta     (sp),y
	pla
	clc
	adc     #<(L0005)
	sta     ptr1
	lda     #$00
	adc     #>(L0005)
	sta     ptr1+1
	lda     #$20
	sta     (ptr1)
	bra     L000C
L000D:	lda     (sp),y
	tay
	lda     #$00
	sta     L0005,y
	jsr     pusha
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2C
	lda     (ptr1),y
	jsr     _gotoxy
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     pushax
	lda     #$4F
	jsr     pusha
	lda     #$00
	clc
	ldy     #$08
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$33
	lda     (ptr1),y
	jsr     _editline2
	jsr     stax0sp
	lda     #<(L0007)
	ldx     #>(L0007)
	jsr     pushax
	jsr     _pack_string
	jsr     _getmem
	ldy     #$02
	jsr     staxysp
	cpx     #$00
	jne     L0060
	cmp     #$00
	jne     L0060
	bra     L002F
L002D:	jsr     _bell
	jsr     _message
	jsr     _waitkey
L002F:	jsr     _quit
	cpx     #$FF
	jne     L0060
	cmp     #$FF
	beq     L002D
	jmp     L0060
L0008:	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     sreg
	stx     sreg+1
	lda     #$00
	clc
	ldy     #$07
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	jsr     aslax1
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	jsr     ldaxi
	jsr     _expand_string
	lda     #$00
	jsr     pusha
	clc
	ldy     #$06
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2C
	lda     (ptr1),y
	jsr     _gotoxy
	lda     #<(L0005)
	ldx     #>(L0005)
	jsr     pushax
	lda     #$4F
	jsr     pusha
	lda     #$00
	clc
	ldy     #$08
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$33
	lda     (ptr1),y
	jsr     _editline2
	jsr     stax0sp
	lda     #<(L0007)
	ldx     #>(L0007)
	jsr     pushax
	jsr     _pack_string
	lda     #<(L0007)
	ldx     #>(L0007)
	jsr     pushax
	ldy     #$08
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     sreg
	stx     sreg+1
	lda     #$00
	clc
	ldy     #$07
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	jsr     aslax1
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	jsr     ldaxi
	jsr     _regetmem
	ldy     #$02
	jsr     staxysp
	cpx     #$00
	bne     L0060
	cmp     #$00
	bne     L0060
	bra     L0061
L005F:	jsr     _bell
	jsr     _message
	jsr     _waitkey
L0061:	jsr     _quit
	cpx     #$FF
	bne     L0060
	cmp     #$FF
	beq     L005F
L0060:	ldy     #$06
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     sreg
	stx     sreg+1
	lda     #$00
	clc
	ldy     #$05
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	jsr     aslax1
	clc
	adc     sreg
	sta     ptr1
	txa
	adc     sreg+1
	sta     ptr1+1
	ldy     #$03
	jsr     ldaxysp
	sta     (ptr1)
	ldy     #$01
	txa
	sta     (ptr1),y
	ldy     #$06
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     sreg
	stx     sreg+1
	lda     #$00
	clc
	ldy     #$05
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	jsr     aslax1
	clc
	adc     sreg
	pha
	txa
	adc     sreg+1
	tax
	pla
	jsr     pushw
	lda     #<(L0007)
	ldx     #>(L0007)
	jsr     _strcpy
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldy     #$03
	lda     (ptr1),y
	beq     L0071
	ldy     #$08
	jsr     pushwysp
	lda     #$01
	tay
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$34
	jsr     staspidx
L0071:	ldy     #$08
	jsr     pushwysp
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$04
	lda     (ptr1),y
	ldy     #$01
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$33
	jsr     staspidx
	jsr     ldax0sp
	jmp     incsp7

.endproc

