;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_gotoxy
	.import		_print
	.import		_blank_line
	.import		_vport_top
	.import		_vport_bot
	.import		_expand_string
	.export		_fill_vport

; ---------------------------------------------------------------
; unsigned char __near__ fill_vport (__near__ struct fileinfo *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_fill_vport: near

.segment	"CODE"

	jsr     pushax
	ldy     #$5A
	jsr     subysp
	lda     _vport_bot+1
	sta     ptr1+1
	lda     _vport_bot
	sta     ptr1
	lda     (ptr1)
	jsr     pusha0
	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     (ptr1)
	jsr     tossuba0
	ldy     #$58
	jsr     staxysp
	lda     #$00
	clc
	ldy     #$5A
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2B
	lda     (ptr1),y
	sec
	ldy     #$58
	sbc     (sp),y
	sta     tmp1
	lda     #$00
	iny
	sbc     (sp),y
	ora     tmp1
	bcc     L0007
	beq     L0007
	ldy     #$5D
	jsr     pushwysp
	ldy     #$5A
	lda     (sp),y
	sec
	sbc     #$01
	ldy     #$01
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$2B
	jsr     staspidx
L0007:	lda     #$00
	clc
	ldy     #$5A
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     pushwidx
	lda     #$00
	clc
	ldy     #$5C
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2B
	lda     (ptr1),y
	jsr     tosicmp0
	bcs     L000B
	ldy     #$5D
	jsr     pushwysp
	lda     #$00
	clc
	ldy     #$5C
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$29
	lda     (ptr1),y
	ldy     #$01
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$2B
	jsr     staspidx
L000B:	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     (ptr1)
	sta     sreg
	lda     #$00
	clc
	ldy     #$5A
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2B
	lda     (ptr1),y
	clc
	adc     sreg
	ldy     #$51
	sta     (sp),y
	ldy     #$5B
	jsr     pushwysp
	lda     #$00
	clc
	ldy     #$5C
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2B
	lda     (ptr1),y
	jsr     tossuba0
	ldy     #$56
	jsr     staxysp
	ldy     #$5D
	jsr     pushwysp
	lda     #$00
	clc
	ldy     #$5C
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     pushwidx
	lda     #$00
	clc
	ldy     #$5E
	adc     (sp),y
	sta     ptr1
	lda     #$04
	iny
	adc     (sp),y
	sta     ptr1+1
	ldy     #$2B
	lda     (ptr1),y
	jsr     tossuba0
	ldy     #$01
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$2D
	jsr     staxspidx
	ldy     #$5D
	jsr     pushwysp
	lda     #$00
	clc
	ldy     #$5C
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	sta     ptr1
	stx     ptr1+1
	ldy     #$59
	jsr     ldaxysp
	jsr     decax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	ldy     #$01
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$2F
	jsr     staxspidx
	lda     #$00
	clc
	ldy     #$5A
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2E
	jsr     ldaxidx
	ldy     #$54
	jsr     staxysp
	lda     _vport_top+1
	sta     ptr1+1
	lda     _vport_top
	sta     ptr1
	lda     (ptr1)
	ldx     #$00
	jmp     L0035
L001C:	lda     #$00
	jsr     pusha
	ldy     #$53
	lda     (sp),y
	jsr     _gotoxy
	ldy     #$5B
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	ldy     #$55
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	cpx     #$00
	bne     L003B
	cmp     #$00
	beq     L0026
L003B:	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$5D
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	ldy     #$57
	jsr     ldaxysp
	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	jsr     _expand_string
	lda     sp
	ldx     sp+1
	jsr     _print
	bra     L0030
L0026:	jsr     _blank_line
L0030:	ldy     #$55
	jsr     ldaxysp
	ina
	bne     L0033
	inx
L0033:	ldy     #$54
	jsr     staxysp
	ldy     #$53
	jsr     ldaxysp
	ina
	bne     L0035
	inx
L0035:	ldy     #$52
	jsr     staxysp
	ldy     #$57
	jsr     pushwysp
	lda     #$00
	clc
	ldy     #$5C
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$30
	jsr     ldaxidx
	jsr     tosicmp
	beq     L0039
	bpl     L0038
L0039:	ldy     #$55
	jsr     ldaxysp
	cmp     #$F5
	txa
	sbc     #$01
	bvc     L0021
	eor     #$80
L0021:	jmi     L001C
L0038:	ldy     #$51
	ldx     #$00
	lda     (sp),y
	ldy     #$5C
	jmp     addysp

.endproc

