;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_malloc
	.import		_free
	.import		_strcpy
	.import		_strlen
	.import		_home
	.import		_gotoxy
	.import		_print
	.import		_println
	.import		_blank_line
	.import		_file1
	.import		_file2
	.import		_div_line
	.export		_init_array
	.import		_init_clip
	.export		_message
	.import		_load_file
	.import		_waitkey
	.export		_init_ed
	.export		_free_mem
	.export		_getmem
	.export		_regetmem

.segment	"RODATA"

L005D:
	.byte	$4F,$75,$74,$20,$6F,$66,$20,$6D,$65,$6D,$6F,$72,$79,$20,$65,$72
	.byte	$72,$6F,$72,$21,$00
L006F:
	.byte	$4F,$75,$74,$20,$6F,$66,$20,$6D,$65,$6D,$6F,$72,$79,$20,$65,$72
	.byte	$72,$6F,$72,$2E,$00
L002E:
	.byte	$4C,$6F,$61,$64,$69,$6E,$67,$3A,$20,$00
L001F	:=	L002E+0

; ---------------------------------------------------------------
; void __near__ init_array (__near__ unsigned char * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_array: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldx     #$00
	txa
L0081:	jsr     stax0sp
	cmp     #$F4
	txa
	sbc     #$01
	bvc     L004E
	eor     #$80
L004E:	bpl     L0048
	jsr     ldax0sp
	jsr     aslax1
	clc
	ldy     #$02
	adc     (sp),y
	sta     ptr1
	txa
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
	jsr     ldax0sp
	ina
	bne     L0081
	inx
	bra     L0081
L0048:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ message (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_message: near

.segment	"CODE"

	jsr     pushax
	lda     #$00
	jsr     pusha
	jsr     _gotoxy
	jsr     _blank_line
	lda     #$00
	jsr     pusha
	jsr     _gotoxy
	jsr     ldax0sp
	jsr     _print
	jmp     incsp2

.endproc

; ---------------------------------------------------------------
; void __near__ init_ed (int, __near__ unsigned char * *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_init_ed: near

.segment	"CODE"

	jsr     pushax
	jsr     _home
	jsr     _init_array
	jsr     _init_array
	jsr     _init_clip
	lda     #$01
	sta     _file1+1065
	stz     _file1+1065+1
	sta     _file2+1065
	stz     _file2+1065+1
	sta     _file1+1067
	sta     _file2+1067
	stz     _file1+1076
	stz     _file2+1076
	stz     _file1+1075
	stz     _file2+1075
	lda     #<(_file1)
	ldx     #>(_file1)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$03
	jsr     ldaxidx
	jsr     _strcpy
	jsr     _message
	lda     #<(_file1)
	ldx     #>(_file1)
	jsr     _println
	lda     #<(_file1)
	ldx     #>(_file1)
	jsr     pushax
	jsr     _load_file
	ldy     #$03
	lda     (sp),y
	bne     L0026
	dey
	lda     (sp),y
	cmp     #$03
	bne     L0026
	lda     #<(_file2)
	ldx     #>(_file2)
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ldy     #$05
	jsr     ldaxidx
	jsr     _strcpy
	jsr     _message
	lda     #<(_file2)
	ldx     #>(_file2)
	jsr     _println
	lda     #<(_file2)
	ldx     #>(_file2)
	jsr     pushax
	jsr     _load_file
	lda     #$0C
	sta     _div_line
L0026:	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; void __near__ free_mem (__near__ struct fileinfo *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_free_mem: near

.segment	"CODE"

	jsr     pushax
	jsr     push0
	bra     L003B
L0039:	ldy     #$03
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     ldaxi
	jsr     _free
	ldy     #$03
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	sta     regsave
	stx     regsave+1
	ina
	bne     L0043
	inx
L0043:	ldy     #$02
	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     aslax1
	jsr     tosaddax
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$01
	sta     (ptr1),y
L003B:	ldy     #$03
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	jsr     ldax0sp
	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$01
	ora     (ptr1),y
	jne     L0039
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ getmem (__near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_getmem: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	jsr     _strlen
	ina
	bne     L005B
	inx
L005B:	jsr     _malloc
	jsr     stax0sp
	stx     tmp1
	ora     tmp1
	bne     L0055
	jsr     _message
	jsr     _waitkey
	ldx     #$00
	txa
	jmp     incsp4
L0055:	jsr     ldax0sp
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ regetmem (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_regetmem: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$03
	jsr     ldaxysp
	jsr     _free
	ldy     #$05
	jsr     ldaxysp
	jsr     _strlen
	ina
	bne     L006D
	inx
L006D:	jsr     _malloc
	jsr     stax0sp
	stx     tmp1
	ora     tmp1
	bne     L0067
	jsr     _message
	jsr     _waitkey
	ldx     #$00
	txa
	jmp     incsp6
L0067:	jsr     ldax0sp
	jmp     incsp6

.endproc

