;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_editline
	.import		_gotoxy
	.import		_printf
	.import		_tabstops
	.import		_message
	.import		_waitkey
	.export		_search_string
	.export		_check_match
	.export		_calc_offset
	.export		_debug
	.export		_do_search

.segment	"RODATA"

L000A:
	.byte	$45,$6E,$74,$65,$72,$20,$73,$65,$61,$72,$63,$68,$20,$73,$74,$72
	.byte	$69,$6E,$67,$3A,$00
L0084:
	.byte	$25,$64,$00
L0081:
	.byte	$20,$00

; ---------------------------------------------------------------
; int __near__ search_string (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_search_string: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	ldy     #$05
	jsr     ldaxysp
	ldy     #$00
	bra     L008D
L002E:	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     tosicmp0
	beq     L0033
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     sreg
	stz     sreg+1
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$20
	jsr     decaxy
	cpx     sreg+1
	bne     L0036
	cmp     sreg
	bne     L0036
L0033:	ldy     #$07
	jsr     pushwysp
	jsr     _check_match
	stx     tmp1
	ora     tmp1
	beq     L0036
	jsr     pushw0sp
	jsr     _calc_offset
	jmp     incsp6
L0036:	ldy     #$05
	jsr     ldaxysp
	ina
	bne     L003F
	inx
L003F:	ldy     #$04
L008D:	jsr     staxysp
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$0A
	bne     L002E
	ldx     #$00
	txa
	jmp     incsp6

.endproc

; ---------------------------------------------------------------
; int __near__ check_match (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_check_match: near

.segment	"CODE"

	jsr     pushax
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0044
	inx
L0044:	ldy     #$02
	jsr     staxysp
	jsr     ldax0sp
	ina
	bne     L0046
	inx
L0046:	ldy     #$00
	bra     L0092
L0047:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     pusha0
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jsr     tosicmp0
	beq     L004D
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     sreg
	stz     sreg+1
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$20
	jsr     decaxy
	cpx     sreg+1
	bne     L0091
	cmp     sreg
	beq     L004D
L0091:	ldx     #$00
	txa
	jmp     incsp4
L004D:	jsr     ldax0sp
	ina
	bne     L0051
	inx
L0051:	jsr     stax0sp
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0053
	inx
L0053:	ldy     #$02
L0092:	jsr     staxysp
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	bne     L0047
	tax
	ina
	jmp     incsp4

.endproc

; ---------------------------------------------------------------
; int __near__ calc_offset (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_calc_offset: near

.segment	"CODE"

	jsr     pushax
	jsr     decsp6
	ldx     #$00
	txa
	ldy     #$04
	bra     L0095
L005C:	ldy     #$09
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$09
	bne     L0060
	lda     #<(_tabstops)
	ldy     #$04
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(_tabstops)
	iny
	adc     (sp),y
	sta     ptr1+1
	lda     (ptr1)
	sec
	dey
	sbc     (sp),y
	pha
	lda     #$00
	iny
	sbc     (sp),y
	tax
	pla
	ldy     #$02
	jsr     staxysp
	ldx     #$00
	txa
L0097:	jsr     stax0sp
	ldy     #$02
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	bvc     L0093
	eor     #$80
L0093:	bpl     L009C
	ldy     #$05
	jsr     ldaxysp
	ina
	bne     L006F
	inx
L006F:	ldy     #$04
	jsr     staxysp
	jsr     ldax0sp
	ina
	bne     L0097
	inx
	bra     L0097
L0060:	ldy     #$05
	jsr     ldaxysp
	ina
	bne     L0074
	inx
L0074:	ldy     #$04
	jsr     staxysp
L009C:	ldy     #$09
	jsr     ldaxysp
	ina
	bne     L0076
	inx
L0076:	ldy     #$08
L0095:	jsr     staxysp
	ldy     #$09
	jsr     ldaxysp
	ldy     #$06
	cmp     (sp),y
	txa
	iny
	sbc     (sp),y
	jcc     L005C
	ldy     #$05
	jsr     ldaxysp
	ldy     #$0A
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ debug (int)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_debug: near

.segment	"CODE"

	jsr     pushax
	lda     #$25
	jsr     pusha0
	ldx     #$05
	lda     #$7B
	jsr     pushax
	jsr     decsp2
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	ldy     #$01
	sta     (sp),y
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	sta     (sp)
	jsr     _message
	lda     #<(L0084)
	ldx     #>(L0084)
	jsr     pushax
	ldy     #$0B
	jsr     pushwysp
	ldy     #$04
	jsr     _printf
	jsr     _waitkey
	lda     (sp)
	jsr     pusha
	ldy     #$02
	lda     (sp),y
	jsr     _gotoxy
	jmp     incsp8

.endproc

; ---------------------------------------------------------------
; void __near__ do_search (__near__ struct fileinfo *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_do_search: near

.segment	"BSS"

L0004:
	.res	2,$00
L0006:
	.res	50,$00
L0007:
	.res	2,$00
L0008:
	.res	2,$00

.segment	"CODE"

	jsr     pushax
	jsr     decsp2
	jsr     _message
	lda     #<(L0006)
	ldx     #>(L0006)
	jsr     pushax
	lda     #$30
	jsr     _editline
	sta     L0004
	stx     L0004+1
	lda     #<(L0006+48)
	ldx     #>(L0006+48)
L009E:	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$20
	bne     L0013
	jsr     ldax0sp
	jsr     decax1
	bra     L009E
L0013:	jsr     ldax0sp
	ina
	bne     L001D
	inx
L001D:	jsr     stax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	clc
	ldy     #$02
	adc     (sp),y
	pha
	lda     #$04
	iny
	adc     (sp),y
	tax
	pla
	ldy     #$2A
	jsr     ldaxidx
	sta     L0007
	stx     L0007+1
	ldy     #$03
	jsr     ldaxysp
	ldy     #$41
	jsr     incaxy
	sta     ptr1
	stx     ptr1+1
	lda     L0007
	ldx     L0007+1
	jsr     aslax1
	clc
	adc     ptr1
	pha
	txa
	adc     ptr1+1
	tax
	pla
	jsr     pushw
	jsr     _search_string
	sta     L0008
	stx     L0008+1
	ldy     #$05
	jsr     pushwysp
	lda     L0008
	ldy     #$01
	clc
	pha
	lda     #$04
	adc     (sp),y
	sta     (sp),y
	pla
	ldy     #$33
	jsr     staspidx
	jsr     _debug
	jmp     incsp4

.endproc

