;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.import		_strcpy
	.export		_ck_spaces
	.export		_tabstops
	.export		_expand_string
	.export		_pack_string

.segment	"DATA"

_tabstops:
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$04
	.byte	$08
	.byte	$08
	.byte	$08
	.byte	$08
	.byte	$0C
	.byte	$0C
	.byte	$0C
	.byte	$0C
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$10
	.byte	$14
	.byte	$14
	.byte	$14
	.byte	$14
	.byte	$18
	.byte	$18
	.byte	$18
	.byte	$18
	.byte	$1C
	.byte	$1C
	.byte	$1C
	.byte	$1C
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$20
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$24
	.byte	$28
	.byte	$28
	.byte	$28
	.byte	$28
	.byte	$2C
	.byte	$2C
	.byte	$2C
	.byte	$2C
	.byte	$30
	.byte	$30
	.byte	$30
	.byte	$30
	.byte	$34
	.byte	$34
	.byte	$34
	.byte	$34
	.byte	$38
	.byte	$38
	.byte	$38
	.byte	$38
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$3C
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$40
	.byte	$44
	.byte	$44
	.byte	$44
	.byte	$44
	.byte	$48
	.byte	$48
	.byte	$48
	.byte	$48
	.byte	$4C
	.byte	$4C
	.byte	$4C
	.byte	$4C
	.byte	$4F
	.byte	$4F
	.byte	$4F
	.byte	$4F

; ---------------------------------------------------------------
; __near__ unsigned char * __near__ ck_spaces (__near__ unsigned char *, unsigned char)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_ck_spaces: near

.segment	"CODE"

	jsr     pusha
	jsr     decsp4
	ldy     #$06
	jsr     ldaxysp
	jsr     stax0sp
	ldx     #$00
	lda     #$01
L0148:	ldy     #$02
	jsr     staxysp
	sec
	ldy     #$04
	sbc     (sp),y
	sta     tmp1
	txa
	sbc     #$00
	ora     tmp1
	jsr     boolugt
	tax
	bne     L0135
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$20
	beq     L013E
	ldx     #$00
	txa
	jsr     stax0sp
	bra     L0135
L013E:	jsr     ldax0sp
	ina
	bne     L0144
	inx
L0144:	jsr     stax0sp
	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0148
	inx
	bra     L0148
L0135:	jsr     ldax0sp
	jmp     incsp7

.endproc

; ---------------------------------------------------------------
; void __near__ expand_string (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_expand_string: near

.segment	"CODE"

	jsr     pushax
	ldy     #$09
	jsr     subysp
	ldy     #$0A
	jsr     ldaxysp
	ldy     #$02
	jsr     staxysp
	ldy     #$0C
	jsr     ldaxysp
	jsr     stax0sp
	ldx     #$00
	txa
	ldy     #$06
	jsr     staxysp
L005A:	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jeq     L007F
	cmp     #$09
	beq     L0061
	cmp     #$0A
	jeq     L0157
	cmp     #$0D
	jeq     L0157
	bra     L0082
L0061:	lda     #<(_tabstops)
	ldy     #$06
	clc
	adc     (sp),y
	sta     ptr1
	lda     #>(_tabstops)
	iny
	adc     (sp),y
	sta     ptr1+1
	ldx     #$00
	lda     (ptr1)
	sec
	dey
	sbc     (sp),y
	pha
	txa
	iny
	sbc     (sp),y
	pla
	iny
	sta     (sp),y
	txa
L014C:	ldy     #$04
	jsr     staxysp
	ldy     #$08
	cmp     (sp),y
	txa
	sbc     #$00
	bcs     L0066
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$20
	sta     (ptr1)
	jsr     ldax0sp
	ina
	bne     L0071
	inx
L0071:	jsr     stax0sp
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L0073
	inx
L0073:	ldy     #$06
	jsr     staxysp
	ldy     #$05
	jsr     ldaxysp
	ina
	bne     L014C
	inx
	bra     L014C
L0066:	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0075
	inx
L0075:	ldy     #$02
	bra     L014B
L007F:	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0081
	inx
L0081:	ldy     #$02
	bra     L014B
L0082:	jsr     pushw0sp
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	jsr     ldax0sp
	ina
	bne     L0086
	inx
L0086:	jsr     stax0sp
L0157:	ldy     #$03
	jsr     ldaxysp
	ina
	bne     L0088
	inx
L0088:	ldy     #$02
	jsr     staxysp
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L008A
	inx
L008A:	ldy     #$06
L014B:	jsr     staxysp
	ldy     #$03
	jsr     ldaxysp
	jsr     decax1
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jne     L005A
	bra     L008F
L008D:	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$20
	sta     (ptr1)
	jsr     ldax0sp
	ina
	bne     L0095
	inx
L0095:	jsr     stax0sp
	ldy     #$07
	jsr     ldaxysp
	ina
	bne     L0097
	inx
L0097:	ldy     #$06
	jsr     staxysp
L008F:	ldy     #$07
	jsr     ldaxysp
	cmp     #$51
	txa
	sbc     #$00
	bvc     L0091
	eor     #$80
L0091:	bmi     L008D
	jsr     ldax0sp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$0D
	jmp     addysp

.endproc

; ---------------------------------------------------------------
; void __near__ pack_string (__near__ unsigned char *, __near__ unsigned char *)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_pack_string: near

.segment	"CODE"

	jsr     pushax
	ldy     #$5C
	jsr     subysp
	lda     sp
	ldx     sp+1
	jsr     pushax
	ldy     #$5F
	jsr     ldaxysp
	jsr     _strcpy
	ldy     #$5F
	jsr     ldaxysp
	ldy     #$55
	jsr     staxysp
	lda     sp
	ldx     sp+1
L0164:	ldy     #$53
	jsr     staxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	beq     L00AB
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L0164
	inx
	bra     L0164
L00AB:	ldy     #$54
	jsr     ldaxysp
	jsr     decax1
	ldy     #$53
	jsr     staxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$20
	beq     L00AB
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L00B1
	inx
L00B1:	ldy     #$53
	jsr     staxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	lda     sp
	ldx     sp+1
	ldy     #$53
	jsr     staxysp
	lda     #$00
	ldy     #$59
	sta     (sp),y
	dey
L0162:	sta     (sp),y
L00B8:	ldy     #$54
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jeq     L00B9
	ldy     #$54
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	jeq     L00B9
	ldy     #$54
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$20
	jeq     L00FE
	cmp     #$22
	beq     L00C5
	cmp     #$27
	jeq     L00DC
	jmp     L0123
L00C5:	ldy     #$59
	lda     (sp),y
	bne     L015D
	ina
	sta     (sp),y
	dey
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L00CD
	inx
L00CD:	ldy     #$55
	jsr     staxysp
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L00CF
	inx
L00CF:	ldy     #$53
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	jmp     L0162
L015D:	lda     #$00
	sta     (sp),y
	dey
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L00D7
	inx
L00D7:	ldy     #$55
	jsr     staxysp
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L00D9
	inx
L00D9:	ldy     #$53
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	jmp     L0162
L00DC:	ldy     #$54
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$27
	bne     L00DD
	ldy     #$54
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$01
	lda     (ptr1),y
	cmp     #$20
	bne     L00DD
	ldy     #$54
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$02
	lda     (ptr1),y
	cmp     #$27
	bne     L00DD
	ldx     #$00
	txa
L0166:	ldy     #$5A
	jsr     staxysp
	cmp     #$03
	txa
	sbc     #$00
	bvc     L00EB
	eor     #$80
L00EB:	jpl     L00B8
	ldy     #$58
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L00F1
	inx
L00F1:	ldy     #$55
	jsr     staxysp
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L00F3
	inx
L00F3:	ldy     #$53
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	sta     (sp),y
	ldy     #$5B
	jsr     ldaxysp
	ina
	bne     L0166
	inx
	bra     L0166
L00DD:	ldy     #$58
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L00F9
	inx
L00F9:	ldy     #$55
	jsr     staxysp
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L00FB
	inx
L00FB:	ldy     #$53
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	jmp     L0162
L00FE:	ldy     #$59
	lda     (sp),y
	beq     L00FF
	dey
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L0104
	inx
L0104:	ldy     #$55
	jsr     staxysp
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L0106
	inx
L0106:	ldy     #$53
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	jmp     L0162
L00FF:	dey
	lda     (sp),y
	tay
	lda     _tabstops,y
	sec
	ldy     #$58
	sbc     (sp),y
	dey
	sta     (sp),y
	dey
	jsr     pushwysp
	ldy     #$59
	lda     (sp),y
	jsr     _ck_spaces
	ldy     #$51
	jsr     staxysp
	cpx     #$00
	bne     L010C
	cmp     #$00
	bne     L010C
	ldy     #$58
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L0116
	inx
L0116:	ldy     #$55
	jsr     staxysp
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L0118
	inx
L0118:	ldy     #$53
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	jmp     L0162
L010C:	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$09
	sta     (ptr1)
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L011E
	inx
L011E:	ldy     #$55
	jsr     staxysp
	ldy     #$52
	jsr     ldaxysp
	ldy     #$53
	jsr     staxysp
	ldy     #$57
	lda     (sp),y
	iny
	clc
	adc     (sp),y
	jmp     L0162
L0123:	ldy     #$58
	jsr     pushwysp
	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldy     #$00
	lda     (ptr1)
	jsr     staspidx
	ldy     #$54
	jsr     ldaxysp
	ina
	bne     L0127
	inx
L0127:	ldy     #$53
	jsr     staxysp
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L0129
	inx
L0129:	ldy     #$55
	jsr     staxysp
	ldy     #$58
	lda     (sp),y
	ina
	jmp     L0162
L00B9:	ldy     #$56
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$0D
	sta     (ptr1)
	ldy     #$56
	jsr     ldaxysp
	ina
	bne     L012E
	inx
L012E:	ldy     #$55
	jsr     staxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	ldy     #$60
	jmp     addysp

.endproc

