;
; File generated by cc65 v 2.18 - N/A
;
	.fopt		compiler,"cc65 v 2.18 - N/A"
	.setcpu		"65C02"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.export		_waitkey

; ---------------------------------------------------------------
; int __near__ waitkey (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_waitkey: near

.segment	"CODE"

	ldx     #$C0
	lda     #$00
	jsr     pushax
	lda     #$10
	jsr     pushax
	jsr     decsp2
L0004:	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     (ptr1)
	cmp     #$80
	bcc     L0004
	ldy     #$05
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	ldx     #$00
	lda     (ptr1)
	ldy     #$80
	jsr     decaxy
	jsr     stax0sp
	ldy     #$03
	jsr     ldaxysp
	sta     ptr1
	stx     ptr1+1
	lda     #$00
	sta     (ptr1)
	jsr     ldax0sp
	jmp     incsp6

.endproc

